version: "3.5"
services:
  web:
    container_name: dockerdev
    build: ./
    ports:
      - "8443:8443"
    environment:
      DD_DB_HOST: db
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    depends_on:
      - db
    restart: always
  db:
    container_name: dockerdev-db
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: golang
      POSTGRES_PASSWORD: golang
      POSTGRES_DB: golang
    restart: always
